#############################################################################
# Makefile for building: Innovation_GUI
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Oct 27 13:53:53 2014
# Project:  Innovation_GUI.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Innovation_GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED 
CFLAGS        = -pg -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES) -pg
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.INCLUDEPATH -I+= -I/usr/local/qwt-5.2.1/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -pg
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/local/qwt-5.2.1/lib/ -lqwt -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = curvePlot.cpp \
		curveItem.cpp \
		spectrogramPlot.cpp \
		spectrogramItem.cpp \
		main.cpp \
		mainWindow.cpp \
		settingWindow.cpp \
		tcpserver.cpp \
		tcpthread.cpp \
		func.cpp moc_curvePlot.cpp \
		moc_spectrogramPlot.cpp \
		moc_mainWindow.cpp \
		moc_settingWindow.cpp \
		moc_tcpserver.cpp \
		moc_tcpthread.cpp \
		qrc_curve.cpp \
		qrc_resource.cpp \
		qrc_source.cpp
OBJECTS       = curvePlot.o \
		curveItem.o \
		spectrogramPlot.o \
		spectrogramItem.o \
		main.o \
		mainWindow.o \
		settingWindow.o \
		tcpserver.o \
		tcpthread.o \
		func.o \
		moc_curvePlot.o \
		moc_spectrogramPlot.o \
		moc_mainWindow.o \
		moc_settingWindow.o \
		moc_tcpserver.o \
		moc_tcpthread.o \
		qrc_curve.o \
		qrc_resource.o \
		qrc_source.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Innovation_GUI.pro
QMAKE_TARGET  = Innovation_GUI
DESTDIR       = 
TARGET        = Innovation_GUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Innovation_GUI.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Innovation_GUI.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Innovation_GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Innovation_GUI1.0.0 || $(MKDIR) .tmp/Innovation_GUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Innovation_GUI1.0.0/ && $(COPY_FILE) --parents curvePlot.h curveItem.h spectrogramPlot.h spectrogramItem.h def.h mainWindow.h pixmaps.h settingWindow.h tcpserver.h tcpthread.h func.h images/clear.xpm .tmp/Innovation_GUI1.0.0/ && $(COPY_FILE) --parents qrc/curve.qrc qrc/resource.qrc qrc/source.qrc .tmp/Innovation_GUI1.0.0/ && $(COPY_FILE) --parents curvePlot.cpp curveItem.cpp spectrogramPlot.cpp spectrogramItem.cpp main.cpp mainWindow.cpp settingWindow.cpp tcpserver.cpp tcpthread.cpp func.cpp .tmp/Innovation_GUI1.0.0/ && (cd `dirname .tmp/Innovation_GUI1.0.0` && $(TAR) Innovation_GUI1.0.0.tar Innovation_GUI1.0.0 && $(COMPRESS) Innovation_GUI1.0.0.tar) && $(MOVE) `dirname .tmp/Innovation_GUI1.0.0`/Innovation_GUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Innovation_GUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_curvePlot.cpp moc_spectrogramPlot.cpp moc_mainWindow.cpp moc_settingWindow.cpp moc_tcpserver.cpp moc_tcpthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_curvePlot.cpp moc_spectrogramPlot.cpp moc_mainWindow.cpp moc_settingWindow.cpp moc_tcpserver.cpp moc_tcpthread.cpp
moc_curvePlot.cpp: def.h \
		curvePlot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) curvePlot.h -o moc_curvePlot.cpp

moc_spectrogramPlot.cpp: spectrogramPlot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spectrogramPlot.h -o moc_spectrogramPlot.cpp

moc_mainWindow.cpp: tcpserver.h \
		tcpthread.h \
		curvePlot.h \
		def.h \
		spectrogramPlot.h \
		mainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainWindow.h -o moc_mainWindow.cpp

moc_settingWindow.cpp: settingWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settingWindow.h -o moc_settingWindow.cpp

moc_tcpserver.cpp: tcpthread.h \
		tcpserver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tcpserver.h -o moc_tcpserver.cpp

moc_tcpthread.cpp: tcpthread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tcpthread.h -o moc_tcpthread.cpp

compiler_rcc_make_all: qrc_curve.cpp qrc_resource.cpp qrc_source.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_curve.cpp qrc_resource.cpp qrc_source.cpp
qrc_curve.cpp: qrc/curve.qrc \
		images/splash.png \
		images/new.png \
		images/find.png \
		images/cut.png \
		images/copy.png \
		images/icon.png \
		images/gotocell.png \
		images/save.png \
		images/paste.png \
		images/264.png \
		images/cancel.png \
		images/268.png \
		images/open.png
	/usr/bin/rcc -name curve qrc/curve.qrc -o qrc_curve.cpp

qrc_resource.cpp: qrc/resource.qrc \
		qss/style3.qss \
		qss/abc.qss \
		qss/style.qss \
		qss/style4.qss \
		qss/style2.qss \
		png/mount.png \
		png/130F63920b0-13E3.png \
		png/com.yiyijiu.taskmanager.activity.png \
		png/130EM33L10-2T28.png \
		png/Jia30754201106091800461.png \
		png/IMG_20120326_215357.png \
		png/personal-computer-03.png \
		png/Jia30754201106091800464.png
	/usr/bin/rcc -name resource qrc/resource.qrc -o qrc_resource.cpp

qrc_source.cpp: qrc/source.qrc \
		qss/setup.png \
		qss/frame.png \
		qss/branch-more.png \
		qss/close.png \
		qss/spinup.png \
		qss/radiobutton_unchecked_hover.png \
		qss/up_arrow_disabled.png \
		qss/maximized_hover.png \
		qss/checkbox_unchecked.png \
		qss/style4.qss \
		qss/phonegui.qss \
		qss/formskin.png \
		qss/minimize.png \
		qss/branch-open.png \
		qss/abc.qss \
		qss/up_arrow_hover.png \
		qss/checkbox_unchecked_hover.png \
		qss/checkbox_checked.png \
		qss/left_arrow.png \
		qss/down_arrow_hover.png \
		qss/right_arrow.png \
		qss/spindown_pressed.png \
		qss/radiobutton_checked_hover.png \
		qss/sizegrip1.png \
		qss/phonegui.qss.bak \
		qss/spinup_pressed.png \
		qss/spindown_off.png \
		qss/maximized.png \
		qss/vline.png \
		qss/no.qss \
		qss/down_arrow.png \
		qss/minimize_hover.png \
		qss/maximize.png \
		qss/checkbox_checked_pressed.png \
		qss/branch-end.png \
		qss/left_arrow_hover.png \
		qss/style2.qss \
		qss/sizegrip.png \
		qss/style.qss \
		qss/spindown_hover.png \
		qss/branch-more1.png \
		qss/down_arrow_disabled.png \
		qss/downarrow.png \
		qss/spinup_off.png \
		qss/spinup_hover.png \
		qss/radiobutton_checked_pressed.png \
		qss/close_hover.png \
		qss/spindown.png \
		qss/branch-closed.png \
		qss/checkbox_unchecked_pressed.png \
		qss/checkbox_checked_hover.png \
		qss/mask.png \
		qss/radiobutton_unchecked_pressed.png \
		qss/style3.qss \
		qss/maximize_hover.png \
		qss/radiobutton_unchecked.png \
		qss/radiobutton_checked.png \
		qss/up_arrow.png \
		qss/right_arrow_hover.png \
		qss/abc_satellite.qss \
		png/130F63920b0-13E3.png \
		png/mount.png \
		png/com.yiyijiu.taskmanager.activity.png \
		png/130EM33L10-2T28.png \
		png/NextMenuButtonIcon.png \
		png/Jia30754201106091800461.png \
		png/IMG_20120326_215357.png \
		png/personal-computer-03.png \
		png/Jia30754201106091800464.png \
		png/PreviousMenuButtonIcon.png
	/usr/bin/rcc -name source qrc/source.qrc -o qrc_source.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

curvePlot.o: curvePlot.cpp curvePlot.h \
		def.h \
		func.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curvePlot.o curvePlot.cpp

curveItem.o: curveItem.cpp def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curveItem.o curveItem.cpp

spectrogramPlot.o: spectrogramPlot.cpp spectrogramPlot.h \
		spectrogramItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectrogramPlot.o spectrogramPlot.cpp

spectrogramItem.o: spectrogramItem.cpp spectrogramItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spectrogramItem.o spectrogramItem.cpp

main.o: main.cpp mainWindow.h \
		tcpserver.h \
		tcpthread.h \
		curvePlot.h \
		def.h \
		spectrogramPlot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainWindow.h \
		tcpserver.h \
		tcpthread.h \
		curvePlot.h \
		def.h \
		spectrogramPlot.h \
		settingWindow.h \
		pixmaps.h \
		images/clear.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

settingWindow.o: settingWindow.cpp settingWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingWindow.o settingWindow.cpp

tcpserver.o: tcpserver.cpp tcpserver.h \
		tcpthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o tcpserver.cpp

tcpthread.o: tcpthread.cpp tcpthread.h \
		def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpthread.o tcpthread.cpp

func.o: func.cpp func.h \
		def.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o func.o func.cpp

moc_curvePlot.o: moc_curvePlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_curvePlot.o moc_curvePlot.cpp

moc_spectrogramPlot.o: moc_spectrogramPlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spectrogramPlot.o moc_spectrogramPlot.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_settingWindow.o: moc_settingWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingWindow.o moc_settingWindow.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_tcpthread.o: moc_tcpthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpthread.o moc_tcpthread.cpp

qrc_curve.o: qrc_curve.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_curve.o qrc_curve.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

qrc_source.o: qrc_source.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_source.o qrc_source.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

